version: "3.7"
services:
  bgtracker:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - '/app/node_modules'
